runtime: python
env: flex
entrypoint: gunicorn api:app

service: api

runtime_config:
  python_version: 3

endpoints_api_service:
  name: debuggerbasedmonitoring.appspot.com
  rollout_strategy: managed
